name: my_workflows

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.0"
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          make install

      - name: Run linter
        run: |
          make lint

      - name: Run test coverage
        run: |
          make test-coverage